services:
  lab-runner:
    build:
      context: ./jupyter  # Relative path to the jupyter folder
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/home/jovyan/work  # Mounts a local folder for your notebooks
    depends_on:
      - mongodb
    user: "1000:100" #Set user and group ID.

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mongodb

  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: